export const listItems = [
  {
    url: "/course/react-the-complete-guide-incl-redux/",
    price: 129000,
    num_reviews: 205899,
    num_subscribers: 595942,
    title: "React - The Complete Guide 2024 (incl. React Router & Redux)",
    num_asset_video_i: "854",
    rating: 4.630371,
    num_simple_quiz_i: "8",
    primary_labelIds_is: "[7450]",
    image_100x100:
      "https://img-c.udemycdn.com/course/100x100/1362070_b9a1_2.jpg",
    ppi_all_funnels_f: "0.003862345",
    image_304x171:
      "https://img-c.udemycdn.com/course/304x171/1362070_b9a1_2.jpg",
    badge_families: ["bestseller", "bestseller"],
    badge_types: [
      "beginner_top_rated_subcategory_topic_1",
      "best_seller_category_topic",
      "best_seller_subcategory_topic",
    ],
    course_subcategory_encoded_i: "3",
    lang_s: "en",
    image_125_H: "https://img-c.udemycdn.com/course/125_H/1362070_b9a1_2.jpg",
    image_240x135:
      "https://img-c.udemycdn.com/course/240x135/1362070_b9a1_2.jpg",
    num_practice_test_i: "0",
    hrs_of_content_f: "68.236",
    _class: "course",
    num_resources_download_i: "928",
    is_practice_test_course: false,
    image_480x270:
      "https://img-c.udemycdn.com/course/480x270/1362070_b9a1_2.jpg",
    objectives_summary: [
      "Learn React from the ground up and finish the course as an advanced React developer",
      "Build multiple high-quality demo apps, including a fullstack app built with NextJS",
      "Join more than 800,000 students in this course & more than 2,500,000 students I taught across all my courses",
    ],
    visible_instructors: [
      {
        title: "Academind by Maximilian Schwarzmüller",
        display_name: "Academind by Maximilian Schwarzmüller",
      },
      {
        title: "Maximilian Schwarzmüller",
        display_name: "Maximilian Schwarzmüller",
      },
    ],
    num_published_lectures: 695,
    id: 1362070,
    is_paid: true,
    num_coding_exercise_i: "37",
    hrs_of_video_f: "67.65972",
    headline:
      "Dive in and learn <strong>React</strong>.js from scratch! Learn <strong>React</strong>, Hooks, Redux, <strong>React</strong> Router, Next.js, Best Practices and way more!",
    predictive_score: 3.4108829498291016,
    relevancy_score: 3820.06201171875,
    tracking_id: "4RvMFL6YQpG4I7J1KQkU_g",
    content_info: "68,5 total jam",
    instructional_level_simple: "Semua Tingkat",
    badges: [
      {
        _class: "ds_course_badge",
        id: "0f36b9879dc1408da12ccaab60e46ab4",
        badge_text: "Bestseller",
        badge_family: "bestseller",
        context_info: {
          category: {
            id: 288,
            title: "Pengembangan",
            url: "/courses/development/",
            tracking_object_type: "cat",
          },
          subcategory: null,
          label: {
            id: 7450,
            display_name: "React JS",
            title: "React JS",
            topic_channel_url: "/topic/react/",
            url: "/topic/react/",
            tracking_object_type: "cl",
          },
        },
      },
    ],
    is_in_user_subscription: false,
    learn_url: "/course/react-the-complete-guide-incl-redux/learn/",
    buyable_object_type: "course",
    free_course_subscribe_url: null,
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    num_coding_exercises: 37,
    is_coding_exercises_badge_eligible: true,
  },
  {
    num_resources_download_i: "6",
    price: 322000,
    num_asset_video_i: "405",
    is_practice_test_course: false,
    id: 4471614,
    lang_s: "en",
    hrs_of_video_f: "67.12222",
    badge_families: ["bestseller", "top_rated", "bestseller"],
    num_reviews: 9790,
    headline:
      "Master modern <strong>React</strong> from beginner to advanced! Context API, <strong>React</strong> Query, Redux Toolkit, Tailwind, advanced patterns",
    rating: 4.781217,
    num_simple_quiz_i: "0",
    image_240x135:
      "https://img-b.udemycdn.com/course/240x135/4471614_361e_5.jpg",
    _class: "course",
    visible_instructors: [
      {
        title: "Jonas Schmedtmann",
        display_name: "Jonas Schmedtmann",
      },
    ],
    num_practice_test_i: "0",
    image_480x270:
      "https://img-b.udemycdn.com/course/480x270/4471614_361e_5.jpg",
    num_published_lectures: 411,
    image_100x100:
      "https://img-b.udemycdn.com/course/100x100/4471614_361e_5.jpg",
    hrs_of_content_f: "67.1813",
    image_304x171:
      "https://img-b.udemycdn.com/course/304x171/4471614_361e_5.jpg",
    image_125_H: "https://img-b.udemycdn.com/course/125_H/4471614_361e_5.jpg",
    objectives_summary: [
      "Become an advanced, confident, and modern React developer from scratch",
      "Build 8+ beautiful projects, including one HUGE professional real-world app",
      "Become job-ready by working with libraries and tools used in professional projects",
    ],
    primary_labelIds_is: "[7450, 7474]",
    url: "/course/the-ultimate-react-course/",
    badge_types: [
      "best_seller_category_topic",
      "top_rated_subcategory_topic",
      "best_seller_subcategory_topic",
    ],
    ppi_all_funnels_f: "0.0027059386",
    num_coding_exercise_i: "0",
    num_subscribers: 56465,
    title: "The Ultimate React Course 2024: React, Redux & More",
    is_paid: true,
    predictive_score: 2.549769401550293,
    relevancy_score: 3050.32275390625,
    tracking_id: "uTWQ3PD2T9ug4aEqkDBFzA",
    content_info: "67 total jam",
    instructional_level_simple: "Semua Tingkat",
    badges: [
      {
        _class: "ds_course_badge",
        id: "856fcac2f1304afbab2d31fac346edf3",
        badge_text: "Bestseller",
        badge_family: "bestseller",
        context_info: {
          category: {
            id: 288,
            title: "Pengembangan",
            url: "/courses/development/",
            tracking_object_type: "cat",
          },
          subcategory: null,
          label: {
            id: 7474,
            display_name: "Redux Framework",
            title: "Redux Framework",
            topic_channel_url: "/topic/redux-framework/",
            url: "/topic/redux-framework/",
            tracking_object_type: "cl",
          },
        },
      },
    ],
    is_in_user_subscription: false,
    learn_url: "/course/the-ultimate-react-course/learn/",
    buyable_object_type: "course",
    free_course_subscribe_url: null,
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    num_coding_exercises: 0,
    is_coding_exercises_badge_eligible: false,
  },
  {
    badge_families: ["top_rated", "top_rated"],
    price: 129000,
    title: "React & TypeScript - The Practical Guide",
    headline:
      "Build type-safe <strong>React</strong> apps & use TypeScript to enhance your components, state management, Redux & side effects code.",
    url: "/course/react-typescript-the-practical-guide/",
    image_240x135: "https://img-c.udemycdn.com/course/240x135/5620946_7c11.jpg",
    num_subscribers: 6229,
    objectives_summary: [
      "Learn how to build React apps with TypeScript",
      "Get a structured introduction to TypeScript",
      "Use both basic & advanced TypeScript concepts",
    ],
    is_practice_test_course: false,
    num_published_lectures: 101,
    hrs_of_content_f: "7.557",
    primary_labelIds_is: "[8124]",
    num_practice_test_i: "0",
    image_304x171: "https://img-c.udemycdn.com/course/304x171/5620946_7c11.jpg",
    badge_types: ["top_rated_category_topic", "top_rated_subcategory_topic"],
    image_480x270: "https://img-c.udemycdn.com/course/480x270/5620946_7c11.jpg",
    num_reviews: 979,
    num_simple_quiz_i: "0",
    num_asset_video_i: "89",
    ppi_all_funnels_f: "0.0036726464",
    rating: 4.7371516,
    num_resources_download_i: "101",
    image_125_H: "https://img-c.udemycdn.com/course/125_H/5620946_7c11.jpg",
    id: 5620946,
    is_paid: true,
    hrs_of_video_f: "7.356111",
    num_coding_exercise_i: "0",
    lang_s: "en",
    image_100x100: "https://img-c.udemycdn.com/course/100x100/5620946_7c11.jpg",
    visible_instructors: [
      {
        title: "Academind by Maximilian Schwarzmüller",
        display_name: "Academind by Maximilian Schwarzmüller",
      },
      {
        title: "Maximilian Schwarzmüller",
        display_name: "Maximilian Schwarzmüller",
      },
    ],
    _class: "course",
    predictive_score: 2.1849608421325684,
    relevancy_score: 2644.790283203125,
    tracking_id: "P-JNC5PyRr-BmIPTTDKDJQ",
    content_info: "7,5 total jam",
    instructional_level_simple: "Menengah",
    badges: [
      {
        _class: "ds_course_badge",
        id: "f6251c37fa8b4ea9bebb64d140cb1d09",
        badge_text: "Peringkat Tertinggi",
        badge_family: "top_rated",
        context_info: {
          category: {
            id: 288,
            title: "Pengembangan",
            url: "/courses/development/",
            tracking_object_type: "cat",
          },
          subcategory: null,
          label: {
            id: 8124,
            display_name: "Typescript",
            title: "Typescript",
            topic_channel_url: "/topic/typescript/",
            url: "/topic/typescript/",
            tracking_object_type: "cl",
          },
        },
      },
    ],
    is_in_user_subscription: false,
    learn_url: "/course/react-typescript-the-practical-guide/learn/",
    buyable_object_type: "course",
    free_course_subscribe_url: null,
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    num_coding_exercises: 0,
    is_coding_exercises_badge_eligible: false,
  },
  {
    image_125_H: "https://img-c.udemycdn.com/course/125_H/2018828_41a9_3.jpg",
    image_100x100:
      "https://img-c.udemycdn.com/course/100x100/2018828_41a9_3.jpg",
    price: 124000,
    num_subscribers: 45149,
    lang_s: "en",
    title: "React 18  Tutorial and Projects Course - 2024 Edition",
    num_practice_test_i: "0",
    id: 2018828,
    is_practice_test_course: false,
    num_resources_download_i: "1067",
    image_240x135:
      "https://img-c.udemycdn.com/course/240x135/2018828_41a9_3.jpg",
    image_304x171:
      "https://img-c.udemycdn.com/course/304x171/2018828_41a9_3.jpg",
    num_coding_exercise_i: "0",
    rating: 4.7380238,
    badge_types: [
      "best_seller_category_topic",
      "best_seller_subcategory_topic",
      "beginner_top_rated_subcategory_topic_1",
      "beginner_top_rated_category_topic_1",
    ],
    headline:
      "Hands-on <strong>React</strong>: Create 25+ Projects. Includes Axios, Router 6, Query 5, Redux Toolkit",
    ppi_all_funnels_f: "0.0016263193",
    num_published_lectures: 778,
    num_asset_video_i: "1044",
    num_reviews: 10326,
    url: "/course/react-tutorial-and-projects-course/",
    primary_labelIds_is: "[7450]",
    course_subcategory_encoded_i: "61",
    visible_instructors: [
      {
        title: "John Smilga",
        display_name: "John Smilga",
      },
    ],
    image_480x270:
      "https://img-c.udemycdn.com/course/480x270/2018828_41a9_3.jpg",
    num_simple_quiz_i: "0",
    hrs_of_video_f: "76.844444",
    objectives_summary: ["Make Great Projects Using React"],
    is_paid: true,
    _class: "course",
    badge_families: ["bestseller", "bestseller", "beginners_choice"],
    hrs_of_content_f: "76.9546",
    predictive_score: 1.6444345712661743,
    relevancy_score: 3060.859375,
    tracking_id: "99A04tq-TzS_lksQ3RN0Aw",
    content_info: "77 total jam",
    instructional_level_simple: "Semua Tingkat",
    badges: [
      {
        _class: "ds_course_badge",
        id: "63296c08cd504773bd00c47f2c2a0abf",
        badge_text: "Bestseller",
        badge_family: "bestseller",
        context_info: {
          category: {
            id: 294,
            title: "TI & Perangkat Lunak",
            url: "/courses/it-and-software/",
            tracking_object_type: "cat",
          },
          subcategory: null,
          label: {
            id: 7450,
            display_name: "React JS",
            title: "React JS",
            topic_channel_url: "/topic/react/",
            url: "/topic/react/",
            tracking_object_type: "cl",
          },
        },
      },
    ],
    is_in_user_subscription: false,
    learn_url: "/course/react-tutorial-and-projects-course/learn/",
    buyable_object_type: "course",
    free_course_subscribe_url: null,
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    num_coding_exercises: 0,
    is_coding_exercises_badge_eligible: false,
  },
  {
    ppi_all_funnels_f: "0.0037456194",
    url: "/course/the-complete-web-development-bootcamp/",
    badge_types: [
      "beginner_top_rated_category_topic_1",
      "best_seller_category_topic",
      "beginner_top_rated_subcategory_topic_1",
      "best_seller_subcategory_topic",
      "best_seller_subcategory",
    ],
    price: 121000,
    rating: 4.7002344,
    hrs_of_video_f: "61.532776",
    hrs_of_content_f: "62.1998",
    badge_families: [
      "beginners_choice",
      "bestseller",
      "bestseller",
      "bestseller",
    ],
    num_simple_quiz_i: "5",
    num_practice_test_i: "0",
    num_coding_exercise_i: "7",
    lang_s: "en",
    image_100x100:
      "https://img-b.udemycdn.com/course/100x100/1565838_e54e_18.jpg",
    image_304x171:
      "https://img-b.udemycdn.com/course/304x171/1565838_e54e_18.jpg",
    course_subcategory_encoded_i: "1",
    headline:
      "Become a Full-Stack Web Developer with just ONE course. HTML, CSS, Javascript, Node, <strong>React</strong>, PostgreSQL, Web3 and DApps",
    visible_instructors: [
      {
        title: "Dr. Angela Yu",
        display_name: "Dr. Angela Yu",
      },
    ],
    num_reviews: 361771,
    is_paid: true,
    image_125_H: "https://img-b.udemycdn.com/course/125_H/1565838_e54e_18.jpg",
    num_resources_download_i: "95",
    image_480x270:
      "https://img-b.udemycdn.com/course/480x270/1565838_e54e_18.jpg",
    title: "The Complete 2024 Web Development Bootcamp",
    num_published_lectures: 375,
    image_240x135:
      "https://img-b.udemycdn.com/course/240x135/1565838_e54e_18.jpg",
    is_practice_test_course: false,
    _class: "course",
    id: 1565838,
    objectives_summary: [
      "Build 16 web development projects for your portfolio, ready to apply for junior developer jobs.",
      "Learn the latest technologies, including Javascript, React, Node and even Web3 development.",
      "After the course you will be able to build ANY website you want.",
    ],
    num_asset_video_i: "501",
    num_subscribers: 1041724,
    primary_labelIds_is: "[8322]",
    predictive_score: 0.8367416262626648,
    relevancy_score: 2682.807861328125,
    tracking_id: "0I9_oP22Tnu5656axd4yZg",
    content_info: "62 total jam",
    instructional_level_simple: "Semua Tingkat",
    badges: [
      {
        _class: "ds_course_badge",
        id: "6df4627ae9a7441b8df5eda1a15592b7",
        badge_text: "Bestseller",
        badge_family: "bestseller",
        context_info: {
          category: {
            id: 288,
            title: "Pengembangan",
            url: "/courses/development/",
            tracking_object_type: "cat",
          },
          subcategory: null,
          label: {
            id: 8322,
            display_name: "Pengembangan Web",
            title: "Pengembangan Web",
            topic_channel_url: "/topic/web-development/",
            url: "/topic/web-development/",
            tracking_object_type: "cl",
          },
        },
      },
    ],
    is_in_user_subscription: false,
    learn_url: "/course/the-complete-web-development-bootcamp/learn/",
    buyable_object_type: "course",
    free_course_subscribe_url: null,
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    num_coding_exercises: 7,
    is_coding_exercises_badge_eligible: false,
  },
  // Page 2
  {
    lang_s: "en",
    price: 129000,
    num_published_lectures: 346,
    image_125_H: "https://img-c.udemycdn.com/course/125_H/2365628_0b60_9.jpg",
    num_asset_video_i: "305",
    num_reviews: 28024,
    badge_families: [],
    hrs_of_content_f: "42.2554",
    ppi_all_funnels_f: "0.0020309153",
    image_480x270:
      "https://img-c.udemycdn.com/course/480x270/2365628_0b60_9.jpg",
    headline:
      "Updated! Become a Senior <strong>React</strong> Developer. Build a massive E-commerce app with Redux, Hooks, GraphQL, Stripe, Firebase",
    num_subscribers: 113604,
    is_paid: true,
    image_100x100:
      "https://img-c.udemycdn.com/course/100x100/2365628_0b60_9.jpg",
    num_coding_exercise_i: "1",
    url: "/course/complete-react-developer-zero-to-mastery/",
    title: "Complete React Developer (w/ Redux, Hooks, GraphQL)",
    rating: 4.527303,
    primary_labelIds_is: "[7450]",
    num_resources_download_i: "48",
    image_304x171:
      "https://img-c.udemycdn.com/course/304x171/2365628_0b60_9.jpg",
    hrs_of_video_f: "41.90333",
    num_simple_quiz_i: "1",
    _class: "course",
    course_subcategory_encoded_i: "1",
    objectives_summary: [
      "Build enterprise level React applications and deploy to production (using React 18!)",
      "Learn to build reactive, performant, large scale applications like a senior developer",
      "Learn the latest features in React including Hooks, Context API, Suspense, React Lazy  + more",
    ],
    num_practice_test_i: "0",
    id: 2365628,
    visible_instructors: [
      {
        title: "Andrei Neagoie",
        display_name: "Andrei Neagoie",
      },
      {
        title: "Yihua Zhang",
        display_name: "Yihua Zhang",
      },
    ],
    image_240x135:
      "https://img-c.udemycdn.com/course/240x135/2365628_0b60_9.jpg",
    badge_types: [],
    is_practice_test_course: false,
    predictive_score: 0.6497985124588013,
    relevancy_score: 2998.986083984375,
    tracking_id: "VN9Qtpc1QZOX-Iyt984NbA",
    content_info: "42,5 total jam",
    instructional_level_simple: "Semua Tingkat",
    badges: [],
    is_in_user_subscription: false,
    learn_url: "/course/complete-react-developer-zero-to-mastery/learn/",
    buyable_object_type: "course",
    free_course_subscribe_url: null,
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    num_coding_exercises: 1,
    is_coding_exercises_badge_eligible: false,
  },
  {
    rating: 4.718641,
    price: 129000,
    num_resources_download_i: "4",
    image_240x135:
      "https://img-c.udemycdn.com/course/240x135/3388158_7a8e_3.jpg",
    num_asset_video_i: "148",
    is_paid: true,
    _class: "course",
    visible_instructors: [
      {
        title: "Yudi krisnandi",
        display_name: "Yudi krisnandi",
      },
    ],
    url: "/course/react-master-class-untuk-semua/",
    num_coding_exercise_i: "0",
    badge_types: [],
    num_reviews: 239,
    image_304x171:
      "https://img-c.udemycdn.com/course/304x171/3388158_7a8e_3.jpg",
    is_practice_test_course: false,
    headline:
      "Belajar <strong>React</strong> dari dasar sampai advanced topik seperti context-api, redux, redux-saga, Ant design, styled-component, dll",
    title: "React Masterclass Untuk Semua",
    num_simple_quiz_i: "0",
    num_practice_test_i: "0",
    primary_labelIds_is: "[7450]",
    ppi_all_funnels_f: "0.0021411886",
    num_published_lectures: 152,
    image_480x270:
      "https://img-c.udemycdn.com/course/480x270/3388158_7a8e_3.jpg",
    course_subcategory_encoded_i: "1",
    hrs_of_content_f: "18.2521",
    badge_families: [],
    hrs_of_video_f: "18.241943",
    lang_s: "id",
    id: 3388158,
    objectives_summary: [
      "Belajar fundamental react dan fitur - fitur terbaru react seperti hooks, context API, dll",
      "Belajar berbagai teknik untuk styling appliksi react",
      "Menggunakan CSS di Javascript dengan styled component",
    ],
    image_125_H: "https://img-c.udemycdn.com/course/125_H/3388158_7a8e_3.jpg",
    num_subscribers: 846,
    image_100x100:
      "https://img-c.udemycdn.com/course/100x100/3388158_7a8e_3.jpg",
    predictive_score: 0.626898467540741,
    relevancy_score: 12350.9560546875,
    tracking_id: "bpL0I5S4RnmdvALtwdeBBQ",
    content_info: "18,5 total jam",
    instructional_level_simple: "Menengah",
    badges: [],
    is_in_user_subscription: false,
    learn_url: "/course/react-master-class-untuk-semua/learn/",
    buyable_object_type: "course",
    free_course_subscribe_url: null,
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    num_coding_exercises: 0,
    is_coding_exercises_badge_eligible: false,
  },
  {
    num_subscribers: 263575,
    url: "/course/react-redux/",
    num_asset_video_i: "1001",
    lang_s: "en",
    price: 129000,
    visible_instructors: [
      {
        title: "Stephen Grider",
        display_name: "Stephen Grider",
      },
    ],
    badge_types: [
      "beginner_top_rated_subcategory_topic_1",
      "beginner_top_rated_category_topic_1",
    ],
    rating: 4.7298203,
    headline:
      "Master <strong>React</strong> and Redux. Apply modern design patterns to build apps with <strong>React</strong> Router, TailwindCSS, Context, and Hooks!",
    num_reviews: 85855,
    primary_labelIds_is: "[7450, 7474]",
    ppi_all_funnels_f: "0.0014119501",
    image_304x171:
      "https://img-b.udemycdn.com/course/304x171/705264_caa9_13.jpg",
    hrs_of_video_f: "43.323334",
    image_125_H: "https://img-b.udemycdn.com/course/125_H/705264_caa9_13.jpg",
    num_resources_download_i: "359",
    title: "Modern React with Redux [2024 Update]",
    hrs_of_content_f: "43.4538",
    is_practice_test_course: false,
    num_published_lectures: 486,
    image_240x135:
      "https://img-b.udemycdn.com/course/240x135/705264_caa9_13.jpg",
    id: 705264,
    num_coding_exercise_i: "11",
    num_practice_test_i: "0",
    image_100x100:
      "https://img-b.udemycdn.com/course/100x100/705264_caa9_13.jpg",
    objectives_summary: [
      "Create dynamic web apps using the latest in web technology",
      "Acquire the programming skills needed to obtain a software engineering job",
      "Practice your skills with many large projects, exercises, and quizzes",
    ],
    num_simple_quiz_i: "17",
    image_480x270:
      "https://img-b.udemycdn.com/course/480x270/705264_caa9_13.jpg",
    is_paid: true,
    badge_families: ["beginners_choice"],
    _class: "course",
    course_subcategory_encoded_i: "1",
    predictive_score: 0.5075474381446838,
    relevancy_score: 3279.736328125,
    tracking_id: "Po_lljhLRauBA8Pk-m5bEg",
    content_info: "43,5 total jam",
    instructional_level_simple: "Semua Tingkat",
    badges: [],
    is_in_user_subscription: false,
    learn_url: "/course/react-redux/learn/",
    buyable_object_type: "course",
    free_course_subscribe_url: null,
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    num_coding_exercises: 11,
    is_coding_exercises_badge_eligible: true,
  },
  {
    badge_types: [
      "best_seller_subcategory_topic",
      "top_rated_subcategory_topic",
      "top_rated_category_topic",
      "best_seller_category_topic",
    ],
    lang_s: "en",
    price: 129000,
    image_480x270:
      "https://img-b.udemycdn.com/course/480x270/5042208_7db9_3.jpg",
    num_published_lectures: 203,
    num_resources_download_i: "5",
    id: 5042208,
    num_coding_exercise_i: "0",
    course_subcategory_encoded_i: "1",
    title: "React JS Masterclass: Zero To Job Ready With 10 Projects",
    num_reviews: 651,
    hrs_of_video_f: "34.893887",
    is_paid: true,
    _class: "course",
    headline:
      "Become <strong>React</strong> Developer: <strong>React</strong> Core, Hooks, APIs,Routing, Context, Reducers, Redux, Firebase, Tailwind, Deployment & More",
    hrs_of_content_f: "34.9063",
    image_100x100:
      "https://img-b.udemycdn.com/course/100x100/5042208_7db9_3.jpg",
    objectives_summary: [
      "Everything you need to become a React developer with basics to advanced concepts, how things works behind the scenes and real projects",
      "Understand fundamentals: Components & Props, State, Hooks, Context & Reducers and more...",
      "Dive Deep with Custom Hooks, Tailwind CSS, React Router, Redux, Firebase, React Skeleton & more...",
    ],
    url: "/course/complete-reactjs-masterclass/",
    image_240x135:
      "https://img-b.udemycdn.com/course/240x135/5042208_7db9_3.jpg",
    num_asset_video_i: "198",
    visible_instructors: [
      {
        title: "Shubham Sarda",
        display_name: "Shubham Sarda",
      },
    ],
    rating: 4.54131,
    num_simple_quiz_i: "0",
    num_practice_test_i: "0",
    num_subscribers: 2256,
    image_125_H: "https://img-b.udemycdn.com/course/125_H/5042208_7db9_3.jpg",
    ppi_all_funnels_f: "0.0011195596",
    primary_labelIds_is: "[7450, 5820, 156870, 7474]",
    image_304x171:
      "https://img-b.udemycdn.com/course/304x171/5042208_7db9_3.jpg",
    is_practice_test_course: false,
    badge_families: ["bestseller", "top_rated", "top_rated", "bestseller"],
    predictive_score: 0.28666698932647705,
    relevancy_score: 2628.85302734375,
    tracking_id: "J5TEpMpeTl6qvUBUtM02VA",
    content_info: "35 total jam",
    instructional_level_simple: "Semua Tingkat",
    badges: [
      {
        _class: "ds_course_badge",
        id: "81ea06d3b9bf43aab6f5bb7e70c3019e",
        badge_text: "Bestseller",
        badge_family: "bestseller",
        context_info: {
          category: {
            id: 288,
            title: "Pengembangan",
            url: "/courses/development/",
            tracking_object_type: "cat",
          },
          subcategory: null,
          label: {
            id: 5820,
            display_name: "Firebase",
            title: "Firebase",
            topic_channel_url: "/topic/firebase/",
            url: "/topic/firebase/",
            tracking_object_type: "cl",
          },
        },
      },
    ],
    is_in_user_subscription: false,
    learn_url: "/course/complete-reactjs-masterclass/learn/",
    buyable_object_type: "course",
    free_course_subscribe_url: null,
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    num_coding_exercises: 0,
    is_coding_exercises_badge_eligible: false,
  },
  {
    num_resources_download_i: "373",
    primary_labelIds_is: "[57548]",
    image_125_H: "https://img-b.udemycdn.com/course/125_H/3873464_403c_3.jpg",
    image_100x100:
      "https://img-b.udemycdn.com/course/100x100/3873464_403c_3.jpg",
    image_480x270:
      "https://img-b.udemycdn.com/course/480x270/3873464_403c_3.jpg",
    hrs_of_video_f: "32.157223",
    id: 3873464,
    ppi_all_funnels_f: "0.0044228756",
    num_practice_test_i: "0",
    image_240x135:
      "https://img-b.udemycdn.com/course/240x135/3873464_403c_3.jpg",
    lang_s: "en",
    price: 129000,
    num_asset_video_i: "342",
    _class: "course",
    badge_families: ["bestseller", "bestseller"],
    num_subscribers: 76152,
    num_simple_quiz_i: "0",
    is_practice_test_course: false,
    visible_instructors: [
      {
        title: "Maximilian Schwarzmüller",
        display_name: "Maximilian Schwarzmüller",
      },
    ],
    is_paid: true,
    num_coding_exercise_i: "0",
    url: "/course/nextjs-react-the-complete-guide/",
    title: "Next.js 14 & React - The Complete Guide",
    num_reviews: 15952,
    objectives_summary: [
      "Learn how to build fullstack React apps with NextJS 14 & the App Router",
      "Build real projects and apply what you learned with hands-on projects and examples",
      "Learn about different ways of building NextJS app - App Router vs Pages Router",
    ],
    rating: 4.6657434,
    headline:
      "Learn NextJS 14 from the ground up and build fullstack <strong>ReactJS</strong> + NextJS apps with the App Router or Pages Router!",
    image_304x171:
      "https://img-b.udemycdn.com/course/304x171/3873464_403c_3.jpg",
    badge_types: [
      "best_seller_category_topic",
      "best_seller_subcategory_topic",
    ],
    hrs_of_content_f: "32.4335",
    course_subcategory_encoded_i: "1",
    num_published_lectures: 359,
    predictive_score: 0.0752069279551506,
    relevancy_score: 3451.824951171875,
    tracking_id: "fOzU2Z5QQOy5SH-p0NCp0g",
    content_info: "32,5 total jam",
    instructional_level_simple: "Semua Tingkat",
    badges: [
      {
        _class: "ds_course_badge",
        id: "6678419f3a6b44f899d1bdf5a26d6343",
        badge_text: "Bestseller",
        badge_family: "bestseller",
        context_info: {
          category: {
            id: 288,
            title: "Pengembangan",
            url: "/courses/development/",
            tracking_object_type: "cat",
          },
          subcategory: null,
          label: {
            id: 57548,
            display_name: "Next.js",
            title: "Next.js",
            topic_channel_url: "/topic/nextjs-p/",
            url: "/topic/nextjs-p/",
            tracking_object_type: "cl",
          },
        },
      },
    ],
    is_in_user_subscription: false,
    learn_url: "/course/nextjs-react-the-complete-guide/learn/",
    buyable_object_type: "course",
    free_course_subscribe_url: null,
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    num_coding_exercises: 0,
    is_coding_exercises_badge_eligible: false,
  },
  {
    headline:
      "Take you coding to the next level with <strong>React</strong>, Redux, Routes, Node js, Express and MongoDB",
    num_published_lectures: 485,
    is_paid: true,
    num_subscribers: 7641,
    num_coding_exercise_i: "0",
    hrs_of_video_f: "75.211945",
    is_practice_test_course: false,
    id: 1411694,
    rating: 4.465206,
    badge_types: [],
    num_asset_video_i: "844",
    image_304x171: "https://img-c.udemycdn.com/course/304x171/1411694_0862.jpg",
    badge_families: [],
    num_reviews: 1534,
    hrs_of_content_f: "75.2765",
    image_480x270: "https://img-c.udemycdn.com/course/480x270/1411694_0862.jpg",
    visible_instructors: [
      {
        title: "Coding Revolution",
        display_name: "Coding Revolution",
      },
    ],
    num_simple_quiz_i: "0",
    num_practice_test_i: "0",
    url: "/course/the-complete-react-fullstack-course/",
    num_resources_download_i: "84",
    lang_s: "en",
    price: 129000,
    image_100x100: "https://img-c.udemycdn.com/course/100x100/1411694_0862.jpg",
    objectives_summary: [
      "You will learn the whole React WebApp building process, from your pc to the server.",
      "Work with nosql databases ( Firebase, MongoDB and Moongoose)",
      "How to deploy applications to services like Firebase and Heroku.",
    ],
    image_125_H: "https://img-c.udemycdn.com/course/125_H/1411694_0862.jpg",
    primary_labelIds_is: "[7450]",
    _class: "course",
    title: "The complete React 18 Fullstack course ( 2024 edition)",
    course_subcategory_encoded_i: "1",
    ppi_all_funnels_f: "0.001501156",
    image_240x135: "https://img-c.udemycdn.com/course/240x135/1411694_0862.jpg",
    predictive_score: -0.08516467362642288,
    relevancy_score: 2450.203125,
    tracking_id: "Znx73JMZTHeYr5OnzuED8A",
    content_info: "75,5 total jam",
    instructional_level_simple: "Semua Tingkat",
    badges: [],
    is_in_user_subscription: false,
    learn_url: "/course/the-complete-react-fullstack-course/learn/",
    buyable_object_type: "course",
    free_course_subscribe_url: null,
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    num_coding_exercises: 0,
    is_coding_exercises_badge_eligible: false,
  },
  {
    course_subcategory_encoded_i: "1",
    badge_families: ["bestseller", "bestseller"],
    hrs_of_video_f: "32.634724",
    ppi_all_funnels_f: "0.004247259",
    id: 5044338,
    is_practice_test_course: false,
    objectives_summary: [
      "React Js Kullanarak Etkili Projeler Yapmayı",
      "React Bootstrap Kullanımını",
      "React Componentlerini Kullanmayı",
    ],
    num_reviews: 758,
    num_practice_test_i: "0",
    primary_labelIds_is: "[7450]",
    image_240x135: "https://img-c.udemycdn.com/course/240x135/5044338_0008.jpg",
    num_simple_quiz_i: "0",
    visible_instructors: [
      {
        title: "Can Boz",
        display_name: "Can Boz",
      },
    ],
    hrs_of_content_f: "32.6347",
    lang_s: "tr",
    image_125_H: "https://img-c.udemycdn.com/course/125_H/5044338_0008.jpg",
    num_subscribers: 4366,
    url: "/course/react-egitimi/",
    num_published_lectures: 214,
    num_resources_download_i: "0",
    image_480x270: "https://img-c.udemycdn.com/course/480x270/5044338_0008.jpg",
    headline:
      "<strong>React</strong> 18 - <strong>React</strong> Component - <strong>React</strong> State - <strong>React</strong> Hooks - <strong>React</strong> Router 6 - <strong>React</strong> Typescript - Redux Toolkit - Context Api",
    is_paid: true,
    num_asset_video_i: "214",
    num_coding_exercise_i: "0",
    image_304x171: "https://img-c.udemycdn.com/course/304x171/5044338_0008.jpg",
    _class: "course",
    image_100x100: "https://img-c.udemycdn.com/course/100x100/5044338_0008.jpg",
    title: "React JS  : Uygulamalı React JS -Redux Eğitimi (2024 Güncel)",
    rating: 4.643167,
    badge_types: [
      "best_seller_subcategory_topic",
      "best_seller_category_topic",
    ],
    predictive_score: -0.954172670841217,
    relevancy_score: 2403.00146484375,
    tracking_id: "EdVPPMoSSimuFq8SvhNFyw",
    content_info: "32,5 total jam",
    instructional_level_simple: "Semua Tingkat",
    badges: [
      {
        _class: "ds_course_badge",
        id: "bc4f48f281544c9d871bc2c2b5e58936",
        badge_text: "Bestseller",
        badge_family: "bestseller",
        context_info: {
          category: {
            id: 288,
            title: "Pengembangan",
            url: "/courses/development/",
            tracking_object_type: "cat",
          },
          subcategory: null,
          label: {
            id: 7450,
            display_name: "React JS",
            title: "React JS",
            topic_channel_url: "/topic/react/",
            url: "/topic/react/",
            tracking_object_type: "cl",
          },
        },
      },
    ],
    is_in_user_subscription: false,
    learn_url: "/course/react-egitimi/learn/",
    buyable_object_type: "course",
    free_course_subscribe_url: null,
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    num_coding_exercises: 0,
    is_coding_exercises_badge_eligible: false,
    price: 129000,
  },
  {
    image_100x100: "https://img-b.udemycdn.com/course/100x100/4427730_5388.jpg",
    num_resources_download_i: "1",
    image_304x171: "https://img-b.udemycdn.com/course/304x171/4427730_5388.jpg",
    num_coding_exercise_i: "0",
    image_125_H: "https://img-b.udemycdn.com/course/125_H/4427730_5388.jpg",
    num_simple_quiz_i: "0",
    num_subscribers: 19743,
    title: "React Front To Back",
    num_asset_video_i: "150",
    image_480x270: "https://img-b.udemycdn.com/course/480x270/4427730_5388.jpg",
    lang_s: "en",
    price: 129000,
    hrs_of_content_f: "19.929",
    badge_types: [],
    ppi_all_funnels_f: "0.0013293346",
    hrs_of_video_f: "19.920834",
    num_published_lectures: 151,
    num_reviews: 5959,
    rating: 4.6008983,
    badge_families: [],
    visible_instructors: [
      {
        title: "Brad Traversy",
        display_name: "Brad Traversy",
      },
    ],
    num_practice_test_i: "0",
    course_subcategory_encoded_i: "1",
    headline:
      "Learn modern <strong>React</strong> by building 4 projects including a Firebase 9 app and a full stack MERN app",
    is_practice_test_course: false,
    primary_labelIds_is: "[7450]",
    is_paid: true,
    id: 4427730,
    url: "/course/react-front-to-back-2022/",
    image_240x135: "https://img-b.udemycdn.com/course/240x135/4427730_5388.jpg",
    _class: "course",
    objectives_summary: [
      "Learn modern React by building 4 projects",
      "Suitable For Both Beginners & Intermediate React Developers",
      "Feedback app with in depth explanation of React fundamentals",
    ],
    predictive_score: -1.1268093585968018,
    relevancy_score: 2871.53662109375,
    tracking_id: "p5OmEA1rQsuIm3w6kTPxUw",
    content_info: "20 total jam",
    instructional_level_simple: "Pemula",
    badges: [],
    is_in_user_subscription: false,
    learn_url: "/course/react-front-to-back-2022/learn/",
    buyable_object_type: "course",
    free_course_subscribe_url: null,
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    num_coding_exercises: 0,
    is_coding_exercises_badge_eligible: false,
  },
  {
    id: 1436092,
    ppi_all_funnels_f: "0.0040111705",
    lang_s: "en",
    price: 129000,
    primary_labelIds_is: "[9884]",
    headline:
      "Use <strong>React</strong> Native and your <strong>React</strong> knowledge to build native iOS and Android Apps - incl. Push Notifications, Hooks, Redux",
    url: "/course/react-native-the-practical-guide/",
    num_subscribers: 176157,
    num_resources_download_i: "289",
    hrs_of_content_f: "28.6302",
    objectives_summary: [
      "Learn how to use ReactJS to build real native mobile apps for iOS and Android",
      "Develop cross-platform (iOS and Android) mobile apps without knowing Swift, ObjectiveC or Java/ Android",
      "Explore React Native basics and advanced features!",
    ],
    badge_types: [
      "best_seller_category_topic",
      "beginner_top_rated_category_topic_2",
      "beginner_top_rated_subcategory_topic_2",
      "best_seller_subcategory_topic",
    ],
    num_published_lectures: 290,
    num_reviews: 37666,
    title: "React Native - The Practical Guide [2024]",
    num_coding_exercise_i: "0",
    _class: "course",
    rating: 4.6936026,
    image_304x171:
      "https://img-c.udemycdn.com/course/304x171/1436092_2024_4.jpg",
    hrs_of_video_f: "28.491943",
    badge_families: ["bestseller", "beginners_choice", "bestseller"],
    is_practice_test_course: false,
    image_100x100:
      "https://img-c.udemycdn.com/course/100x100/1436092_2024_4.jpg",
    image_125_H: "https://img-c.udemycdn.com/course/125_H/1436092_2024_4.jpg",
    image_480x270:
      "https://img-c.udemycdn.com/course/480x270/1436092_2024_4.jpg",
    image_240x135:
      "https://img-c.udemycdn.com/course/240x135/1436092_2024_4.jpg",
    num_asset_video_i: "275",
    num_practice_test_i: "0",
    num_simple_quiz_i: "3",
    is_paid: true,
    visible_instructors: [
      {
        title: "Academind by Maximilian Schwarzmüller",
        display_name: "Academind by Maximilian Schwarzmüller",
      },
      {
        title: "Maximilian Schwarzmüller",
        display_name: "Maximilian Schwarzmüller",
      },
    ],
    course_subcategory_encoded_i: "2",
    predictive_score: -1.173346996307373,
    relevancy_score: 3399.893310546875,
    tracking_id: "DeVJatI3TZOl1T2q8czh3A",
    content_info: "28,5 total jam",
    instructional_level_simple: "Semua Tingkat",
    badges: [
      {
        _class: "ds_course_badge",
        id: "77a24a25feba4478801e4decbca603ec",
        badge_text: "Bestseller",
        badge_family: "bestseller",
        context_info: {
          category: {
            id: 288,
            title: "Pengembangan",
            url: "/courses/development/",
            tracking_object_type: "cat",
          },
          subcategory: null,
          label: {
            id: 9884,
            display_name: "React Native",
            title: "React Native",
            topic_channel_url: "/topic/react-native/",
            url: "/topic/react-native/",
            tracking_object_type: "cl",
          },
        },
      },
    ],
    is_in_user_subscription: false,
    learn_url: "/course/react-native-the-practical-guide/learn/",
    buyable_object_type: "course",
    free_course_subscribe_url: null,
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    num_coding_exercises: 0,
    is_coding_exercises_badge_eligible: false,
  },
  {
    image_480x270:
      "https://img-c.udemycdn.com/course/480x270/1439744_ba20_5.jpg",
    hrs_of_video_f: "16.291666",
    num_reviews: 2575,
    visible_instructors: [
      {
        title: "Brad Schiff",
        display_name: "Brad Schiff",
      },
    ],
    id: 1439744,
    hrs_of_content_f: "16.4308",
    primary_labelIds_is: "[7450]",
    objectives_summary: [
      'The problem React solves and *why* we should use it (aside from "because it\'s popular")',
      "How to create Single Page Applications with React",
      "The ability to keep your code organized and manageable",
    ],
    url: "/course/react-for-the-rest-of-us/",
    course_subcategory_encoded_i: "1",
    rating: 4.81584,
    title: "React For The Rest Of Us",
    badge_families: [],
    badge_types: [],
    num_resources_download_i: "16",
    num_subscribers: 8795,
    _class: "course",
    lang_s: "en",
    price: 129000,
    is_paid: true,
    num_asset_video_i: "73",
    num_practice_test_i: "0",
    image_240x135:
      "https://img-c.udemycdn.com/course/240x135/1439744_ba20_5.jpg",
    num_simple_quiz_i: "0",
    image_100x100:
      "https://img-c.udemycdn.com/course/100x100/1439744_ba20_5.jpg",
    ppi_all_funnels_f: "0.0014226827",
    is_practice_test_course: false,
    image_304x171:
      "https://img-c.udemycdn.com/course/304x171/1439744_ba20_5.jpg",
    num_coding_exercise_i: "0",
    headline:
      "Learn <strong>React</strong> JS to create Single Page Applications (SPA) using modern practices like Context, Reducer, Suspense and more",
    image_125_H: "https://img-c.udemycdn.com/course/125_H/1439744_ba20_5.jpg",
    num_published_lectures: 89,
    predictive_score: -1.1778273582458496,
    relevancy_score: 2610.673583984375,
    tracking_id: "lsvZ-rkZQwS09kBiGEYBzg",
    content_info: "16,5 total jam",
    instructional_level_simple: "Semua Tingkat",
    badges: [],
    is_in_user_subscription: false,
    learn_url: "/course/react-for-the-rest-of-us/learn/",
    buyable_object_type: "course",
    free_course_subscribe_url: null,
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    num_coding_exercises: 0,
    is_coding_exercises_badge_eligible: false,
  },
  {
    num_asset_video_i: "129",
    price: 129000,
    title: "React State Manager - Redux Toolkit, React Query, Redux Saga",
    visible_instructors: [
      {
        title: "Hỏi Dân IT với Eric .",
        display_name: "Hỏi Dân IT với Eric .",
      },
    ],
    num_reviews: 102,
    image_304x171:
      "https://img-c.udemycdn.com/course/304x171/4567790_50e4_2.jpg",
    num_published_lectures: 100,
    objectives_summary: [
      "Học & Hiểu Tư Duy Đứng Sau Việc Quản Lý State của Ứng dụng React",
      "Nắm Vững & Thành Thạo Redux Thuần, cũng như Redux Toolkit",
      "Đá Bay (vì Đã Hiểu) Lý Do Dùng Redux Thunk, Redux Saga Middleware",
    ],
    primary_labelIds_is: "[7474]",
    ppi_all_funnels_f: "1.9775874E-4",
    course_subcategory_encoded_i: "1",
    rating: 4.9356513,
    headline:
      "All in one - Quản Lý State của ứng dụng <strong>React</strong> một cách hiệu quả",
    image_240x135:
      "https://img-c.udemycdn.com/course/240x135/4567790_50e4_2.jpg",
    image_100x100:
      "https://img-c.udemycdn.com/course/100x100/4567790_50e4_2.jpg",
    is_paid: true,
    num_resources_download_i: "4",
    hrs_of_video_f: "12.738611",
    lang_s: "vi",
    image_125_H: "https://img-c.udemycdn.com/course/125_H/4567790_50e4_2.jpg",
    num_subscribers: 484,
    hrs_of_content_f: "12.7531",
    url: "/course/hoidanit-redux-and-redux-toolkit-ultimate/",
    num_coding_exercise_i: "0",
    num_practice_test_i: "0",
    image_480x270:
      "https://img-c.udemycdn.com/course/480x270/4567790_50e4_2.jpg",
    badge_families: ["top_rated", "top_rated"],
    is_practice_test_course: false,
    id: 4567790,
    num_simple_quiz_i: "0",
    badge_types: ["top_rated_subcategory_topic", "top_rated_category_topic"],
    _class: "course",
    predictive_score: -1.1792962551116943,
    relevancy_score: 2085.05224609375,
    tracking_id: "q4gE0ZfEQT6OjGq1BV5l_w",
    content_info: "13 total jam",
    instructional_level_simple: "Semua Tingkat",
    badges: [],
    is_in_user_subscription: false,
    learn_url: "/course/hoidanit-redux-and-redux-toolkit-ultimate/learn/",
    buyable_object_type: "course",
    free_course_subscribe_url: null,
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    num_coding_exercises: 0,
    is_coding_exercises_badge_eligible: false,
  },
  {
    num_resources_download_i: "84",
    num_simple_quiz_i: "1",
    rating: 2,
    is_paid: true,
    is_practice_test_course: false,
    num_coding_exercise_i: "0",
    id: 2887266,
    image_100x100:
      "https://img-b.udemycdn.com/course/100x100/2887266_c696_5.jpg",
    image_304x171:
      "https://img-b.udemycdn.com/course/304x171/2887266_c696_5.jpg",
    headline:
      "Build, deploy, and scale an E-Commerce app using Microservices built with Node, <strong>React</strong>, Docker and Kubernetes",
    badge_families: ["beginners_choice", "bestseller", "bestseller"],
    url: "/course/microservices-with-node-js-and-react/",
    hrs_of_content_f: "54.4602",
    lang_s: "en",
    price: 129000,
    num_published_lectures: 652,
    visible_instructors: [
      {
        title: "Stephen Grider",
        display_name: "Stephen Grider",
      },
    ],
    course_subcategory_encoded_i: "1",
    image_125_H: "https://img-b.udemycdn.com/course/125_H/2887266_c696_5.jpg",
    ppi_all_funnels_f: "0.0024958318",
    badge_types: [
      "beginner_top_rated_category_topic_1",
      "beginner_top_rated_subcategory_topic_1",
      "best_seller_category_topic",
      "best_seller_subcategory_topic",
    ],
    objectives_summary: [
      "Architect large, scalable apps using a collection of microservices",
      "Deploy a multi-service app to the cloud with Docker and Kubernetes",
      "Solve concurrency issues in a distributed systems environment",
    ],
    _class: "course",
    num_reviews: 17307,
    hrs_of_video_f: "53.898056",
    primary_labelIds_is: "[9192]",
    num_practice_test_i: "0",
    image_480x270:
      "https://img-b.udemycdn.com/course/480x270/2887266_c696_5.jpg",
    title: "Microservices with Node JS and React",
    num_asset_video_i: "593",
    num_subscribers: 91091,
    image_240x135:
      "https://img-b.udemycdn.com/course/240x135/2887266_c696_5.jpg",
    predictive_score: -1.2784475088119507,
    relevancy_score: 3042.684814453125,
    tracking_id: "3_yxqu3cSrmy3B2SMJ-lWA",
    content_info: "54,5 total jam",
    instructional_level_simple: "Semua Tingkat",
    badges: [
      {
        _class: "ds_course_badge",
        id: "ed63484caffb43f0ab7eedce635d4c2a",
        badge_text: "Bestseller",
        badge_family: "bestseller",
        context_info: {
          category: {
            id: 288,
            title: "Pengembangan",
            url: "/courses/development/",
            tracking_object_type: "cat",
          },
          subcategory: null,
          label: {
            id: 9192,
            display_name: "Layanan Mikro",
            title: "Layanan Mikro",
            topic_channel_url: "/topic/microservices/",
            url: "/topic/microservices/",
            tracking_object_type: "cl",
          },
        },
      },
    ],
    is_in_user_subscription: false,
    learn_url: "/course/microservices-with-node-js-and-react/learn/",
    buyable_object_type: "course",
    free_course_subscribe_url: null,
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    num_coding_exercises: 0,
    is_coding_exercises_badge_eligible: false,
  },
  {
    num_reviews: 1440,
    price: 129000,
    image_100x100:
      "https://img-c.udemycdn.com/course/100x100/4782518_1d83_3.jpg",
    visible_instructors: [
      {
        title: "Bogdan Stashchuk | Software Engineer, MBA, PhD",
        display_name: "Bogdan Stashchuk | Software Engineer, MBA, PhD",
      },
    ],
    _class: "course",
    num_resources_download_i: "7",
    hrs_of_video_f: "32.511112",
    badge_types: [
      "best_seller_category_topic",
      "top_rated_category_topic",
      "top_rated_subcategory_topic",
      "best_seller_subcategory_topic",
    ],
    hrs_of_content_f: "32.5386",
    is_practice_test_course: false,
    image_240x135:
      "https://img-c.udemycdn.com/course/240x135/4782518_1d83_3.jpg",
    title: "React - Полный Курс по React и Redux",
    image_304x171:
      "https://img-c.udemycdn.com/course/304x171/4782518_1d83_3.jpg",
    num_practice_test_i: "0",
    num_published_lectures: 396,
    objectives_summary: [
      "Вы изучите основные концепции React, такие как Компоненты (Components), JSX (JavaScript Syntax Extension), Свойства (Props) и Состояние (State)",
      "Поймете, как React работает изнутри, как работают функциональные компоненты и как JSX конвертируется в JavaScript с помощью компилятора Babel",
      "Создадите много различных проектов, начиная с простых, направленных на использование отдельных функций React и заканчивая сложными с разными функциями React",
    ],
    course_subcategory_encoded_i: "1",
    primary_labelIds_is: "[7450]",
    badge_families: ["bestseller", "top_rated", "top_rated", "bestseller"],
    num_simple_quiz_i: "0",
    headline:
      "Поймите и изучите все ключевые функции <strong>React</strong>: Компоненты, JSX, свойства, состояние, useState, useEffect, а также Redux",
    image_125_H: "https://img-c.udemycdn.com/course/125_H/4782518_1d83_3.jpg",
    url: "/course/react-ru/",
    num_coding_exercise_i: "0",
    rating: 3.7,
    id: 4782518,
    lang_s: "ru",
    num_asset_video_i: "389",
    num_subscribers: 4128,
    image_480x270:
      "https://img-c.udemycdn.com/course/480x270/4782518_1d83_3.jpg",
    is_paid: true,
    ppi_all_funnels_f: "0.0032997096",
    predictive_score: -1.3167719841003418,
    relevancy_score: 2456.4970703125,
    tracking_id: "ROQ4U_eKQ8eLz44kFtaHrw",
    content_info: "32,5 total jam",
    instructional_level_simple: "Semua Tingkat",
    badges: [
      {
        _class: "ds_course_badge",
        id: "357013ace3404df2865340f6fb3081ff",
        badge_text: "Bestseller",
        badge_family: "bestseller",
        context_info: {
          category: {
            id: 288,
            title: "Pengembangan",
            url: "/courses/development/",
            tracking_object_type: "cat",
          },
          subcategory: null,
          label: {
            id: 7450,
            display_name: "React JS",
            title: "React JS",
            topic_channel_url: "/topic/react/",
            url: "/topic/react/",
            tracking_object_type: "cl",
          },
        },
      },
    ],
    is_in_user_subscription: false,
    learn_url: "/course/react-ru/learn/",
    buyable_object_type: "course",
    free_course_subscribe_url: null,
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    num_coding_exercises: 0,
    is_coding_exercises_badge_eligible: false,
  },
  {
    num_resources_download_i: "37",
    ppi_all_funnels_f: "0.0022548796",
    hrs_of_content_f: "29.434",
    image_100x100: "https://img-b.udemycdn.com/course/100x100/3749464_eaea.jpg",
    badge_types: [],
    badge_families: [],
    primary_labelIds_is: "[7450]",
    hrs_of_video_f: "29.25",
    is_paid: true,
    image_125_H: "https://img-b.udemycdn.com/course/125_H/3749464_eaea.jpg",
    headline:
      "Expand your portfolio of projects by building a complex app with the latest web technologies.",
    num_published_lectures: 415,
    objectives_summary: [
      "Build a portfolio-ready project with React and Typescript",
      "Integrate React and Redux together with Typescript",
      "Simplify state updates with the fabulous Immer library",
    ],
    num_subscribers: 28796,
    num_practice_test_i: "0",
    image_304x171: "https://img-b.udemycdn.com/course/304x171/3749464_eaea.jpg",
    url: "/course/react-and-typescript-build-a-portfolio-project/",
    num_asset_video_i: "382",
    num_reviews: 4594,
    num_simple_quiz_i: "0",
    visible_instructors: [
      {
        title: "Stephen Grider",
        display_name: "Stephen Grider",
      },
    ],
    is_practice_test_course: false,
    title: "React and Typescript: Build a Portfolio Project",
    num_coding_exercise_i: "0",
    rating: 4.6305904,
    image_480x270: "https://img-b.udemycdn.com/course/480x270/3749464_eaea.jpg",
    image_240x135: "https://img-b.udemycdn.com/course/240x135/3749464_eaea.jpg",
    course_subcategory_encoded_i: "1",
    _class: "course",
    lang_s: "en",
    price: 129000,
    id: 3749464,
    predictive_score: -1.346212387084961,
    relevancy_score: 2467.2001953125,
    tracking_id: "HruV2qsvQEaVw1gDCzomtw",
    content_info: "29,5 total jam",
    instructional_level_simple: "Semua Tingkat",
    badges: [],
    is_in_user_subscription: false,
    learn_url: "/course/react-and-typescript-build-a-portfolio-project/learn/",
    buyable_object_type: "course",
    free_course_subscribe_url: null,
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    num_coding_exercises: 0,
    is_coding_exercises_badge_eligible: false,
  },
  {
    image_240x135:
      "https://img-c.udemycdn.com/course/240x135/4467252_61d1_2.jpg",
    num_reviews: 243,
    num_published_lectures: 192,
    image_100x100:
      "https://img-c.udemycdn.com/course/100x100/4467252_61d1_2.jpg",
    objectives_summary: [
      'HỌC đi đôi với "THỰC HÀNH", xây dựng ĐAM MÊ về lập trình với REACT',
      "Tự tin LÀM CHỦ, NẮM VỮNG những KIẾN THỨC cơ bản, cốt lõi nhất của REACT",
      'Có được TƯ DUY lập trình với React, biết cách "SEARCH Google" khi gặp lỗi',
    ],
    ppi_all_funnels_f: "3.0648836E-5",
    badge_families: ["top_rated", "top_rated", "top_rated"],
    _class: "course",
    is_practice_test_course: false,
    num_practice_test_i: "0",
    image_125_H: "https://img-c.udemycdn.com/course/125_H/4467252_61d1_2.jpg",
    num_resources_download_i: "5",
    primary_labelIds_is: "[8322]",
    hrs_of_content_f: "47.1793",
    title: "React Ultimate - React.JS Cơ Bản Từ Z Đến A Cho Beginners",
    num_subscribers: 566,
    lang_s: "vi",
    num_asset_video_i: "185",
    image_480x270:
      "https://img-c.udemycdn.com/course/480x270/4467252_61d1_2.jpg",
    rating: 3,
    num_coding_exercise_i: "0",
    headline:
      "Hiểu và Làm Chủ <strong>React</strong> (Chỉ Học Những Thứ Cần Thiết)",
    is_paid: true,
    badge_types: [
      "top_rated_subcategory_topic",
      "top_rated_category_topic",
      "top_rated_subcategory",
    ],
    course_subcategory_encoded_i: "1",
    visible_instructors: [
      {
        title: "Hỏi Dân IT với Eric .",
        display_name: "Hỏi Dân IT với Eric .",
      },
    ],
    url: "/course/hoidanit-react-basic-ultimate/",
    hrs_of_video_f: "47.172222",
    image_304x171:
      "https://img-c.udemycdn.com/course/304x171/4467252_61d1_2.jpg",
    id: 4467252,
    num_simple_quiz_i: "0",
    predictive_score: -1.3700557947158813,
    relevancy_score: 2120.922119140625,
    tracking_id: "yctHf4HESviK6HvE-EDUvA",
    content_info: "47 total jam",
    instructional_level_simple: "Semua Tingkat",
    badges: [],
    is_in_user_subscription: false,
    learn_url: "/course/hoidanit-react-basic-ultimate/learn/",
    buyable_object_type: "course",
    free_course_subscribe_url: null,
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    num_coding_exercises: 0,
    is_coding_exercises_badge_eligible: false,
    price: 129000,
  },
];
